--1
select first_name||' '||last_name,salary,COMMISSION_PCT,HIRE_DATE  
from hr.employees 
where salary<10000;
--2
SELECT DISTINCT(CITY) 
FROM HR.LOCATIONS 
ORDER BY CITY;
--3
SELECT FIRST_NAME,HIRE_DATE,JOB_ID 
FROM HR.EMPLOYEES 
JOIN HR.JOBS 
ON JOBS.JOBS_ID=EMPLOYEES.JOB_ID 
WHERE (JOB_TITLE='IT Programmer' 
OR JOB_TITLE='Sales Manager') 
AND (HIRE_DATE BETWEEN '2002' AND '2005');
--4
SELECT * FROM HR.JOBS 
ORDER BY JOB_TITLE DESC;
--5
SELECT * FROM HR.EMPLOYEES 
WHERE COMMISSION_PCT IS NULL 
AND SALARY BETWEEN 5000 AND 10000 
AND DEPARTMENT_ID='30';
--6
select * from hr.employees 
where hire_date>'01-jan-2008';
--7
SELECT * FROM HR.EMPLOYEES 
WHERE EMPLOYEE_ID='150' 
OR EMPLOYEE_ID='160' 
OR EMPLOYEE_ID='170';
--8
SELECT * FROM HR.EMPLOYEES 
WHERE FIRST_NAME LIKE 'S%'  
OR LAST_NAME LIKE 'S%';
--9
SELECT LENGTH(first_name) 
from hr.employees 
where last_name like '___b%';

